<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="exDWORD_TO_STRF" Id="{9cfa1c0e-acd8-4271-a8c7-674aa710cdd7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION exDWORD_TO_STRF : STRING(20)
VAR_INPUT
	IN: DWORD;
	N: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* limit N to max 20 characters *)
(* convert dword to string first and cut to length N *)
exDWORD_TO_STRF := exFIX(DWORD_TO_STRING(in),LIMIT(0,N,20),48,1);


(* revision history
hm	26. jan.2007	rev 1.0		
	original version

hm	29. mar. 2008	rev 1.1
	changed STRING to STRING(20)
	limit the output string to max 20 digits
*)
]]></ST>
    </Implementation>
    <LineIds Name="exDWORD_TO_STRF">
      <LineId Id="3" Count="12" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>