<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="exEVEN" Id="{f8d2a4eb-58a3-4a3f-a4a8-29539656f33a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION exEVEN : BOOL
VAR_INPUT
	in: DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[exEVEN := NOT in.0;

(* revision history
hm	1. oct 2006	rev 1.0
	ORIGINAL VERSION

hm	01.12.2007	rev 1.1
	changed code for improved performance

hm	21. mar. 2008	rev 1.2
	changed type of input IN from INT to DINT
*)]]></ST>
    </Implementation>
    <LineIds Name="exEVEN">
      <LineId Id="3" Count="10" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>