<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="exF_POWER" Id="{630ecc23-a5d9-4c92-886f-959580e94731}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION exF_POWER : REAL
VAR_INPUT
	a: REAL;
	x: REAL;
	n: REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[exF_POWER := a * EXPT(X, N);
]]></ST>
    </Implementation>
    <LineIds Name="exF_POWER">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>