<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="exRDM2" Id="{7ca02374-6815-456d-8aa0-77895593ca0c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION exRDM2 : INT
VAR_INPUT
	last: INT;
	low: INT;
	high: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[exRDM2 := TRUNC_INT(exRDM(exFRACT(last * math.PI)) * (high - low + 1)) + low;

(* revision history
hm		29. feb 2008		rev 1.0
	original version

hm		18. oct. 2008		rev 1.1
	using math constants

*)]]></ST>
    </Implementation>
    <LineIds Name="exRDM2">
      <LineId Id="3" Count="8" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>