<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="PcTransmit" Id="{fa84f91d-0024-00c8-17d0-8bb7ea7a8520}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PcTransmit
VAR
	fbPcTransmit_0 : fbPcTransmit;
	//fbLogTransmitMQTT : fbLogTransmitMQTT;
	isMqtt:BOOL;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[

IF isMqtt THEN
	//fbLogTransmitMQTT();
ELSE
	fbPcTransmit_0();
END_IF
]]></ST>
    </Implementation>
    <LineIds Name="PcTransmit">
      <LineId Id="11" Count="0" />
      <LineId Id="18" Count="1" />
      <LineId Id="30" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>