<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="fb_IO_Basic" Id="{b9dc89ab-8c33-4bb3-8945-785bc1d3fd3f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_IO_Basic
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fb_IO_Basic">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>