<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="putUint" Id="{0797683a-1211-018e-1d9c-09e54da39ce9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION putUint : BOOL
	VAR_INPUT
		uintVar : UINT;
	END_VAR
	VAR_IN_OUT
		bufferRef : POINTER TO USINT;
	END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[memcpy(bufferRef, ADR(uintVar), SIZEOF(UINT));
bufferRef := bufferRef + SIZEOF(UINT);
putUint := TRUE;]]></ST>
    </Implementation>
    <LineIds Name="putUint">
      <LineId Id="15" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>