<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="putUdint" Id="{ecab3789-ee9c-02bc-3240-0c21f377453e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION putUdint : BOOL
	VAR_INPUT
		udintVar : UDINT;
	END_VAR
	VAR_IN_OUT
		bufferRef : POINTER TO USINT;
	END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	memcpy(bufferRef, ADR(udintVar), SIZEOF(UDINT));
	bufferRef := bufferRef + SIZEOF(UDINT);
	putUdint := TRUE;]]></ST>
    </Implementation>
    <LineIds Name="putUdint">
      <LineId Id="13" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>